### ISSUE TITLE
Need to create two crates when registering on crates.io

### ISSUE THREAD

**Issue by rezural** [NiklasEi/bevy_game_template#12]
Hey,

I like the layout of the template! Omakase..

One things is that when comes time to publish to crates.io, I needed to create two crates (this may have caused a technical issue, or I just didnt want to publish 2 crates).

Is there a way to roll the game_plugin crate into the game crate?

I moved the code myself from the game_plugin crate, but I would prefer a better solution if I keep using the template, as it was a little tricky.

Thanks.

**Comment by NiklasEi** [comment]
Hi, glad you like it :slightly_smiling_face: 

The two crates in the template are not really supposed to be published. Note that they both have `publish: false` set.

I am not sure what your use case for publishing a game on crates.io is, but if you want to move everything in one crate, simply copy all files from `game_plugin/src` into `src`. The only other changes necessary would be an adaption of the imports in `main.rs` and removal of the `game_plugin` crate in `cargo.toml`.

For most users, I would expect that the extra crate makes no difference since they most likely do not publish anything on crates.io. The goal was to split the game into a small executable crate that just starts the process and otherwise uses logic from a library crate (if the example game would grow a lot one could think about adding more and more library crates, as long as the split makes sense).

**Comment by rezural** [comment]
Of course. Of coursse. Good points.

I am working more on a utility, but still, the users are probably not going to be rustaceans so much (if there is more than 1 user :D).

I have moved the game_plugin/src into src, which probably makes sense for this, as I wil publish on cargo, but it is definately a corner case.

Love the github actions btw. Flawless. Thanks heaps, you saved me a bunch of time.
